#!/usr/bin/env bash
# lib.sh — shared helpers for the manual QA flow.
#
# Source this file from every other manual-qa/*.sh script:
#
#   source "$(dirname "$0")/lib.sh"
#
# Public surface (functions only — no globals are exported except
# FLOWAI_MANUAL_QA_RUN_DIR):
#
#   Strict mode + tracing
#     mq::enter_strict_mode       — enable errexit/pipefail/nounset + umask 0077
#     mq::trace                   — print a timestamped log line to stderr
#     mq::fail                    — print a diagnostic + exit 1
#     mq::require_cmd             — fail when $1 is not on PATH
#     mq::require_rootless_podman — fail when XDG_RUNTIME_DIR/podman/podman.sock is absent
#
#   Local dotenv loader (NO source / NO eval)
#     mq::load_dotenv <path>      — parse a single KEY=VALUE file safely
#     mq::load_manual_qa_dotenv   — load <manual-qa>/.env when present
#
#   Runtime state (under ${FLOWAI_MANUAL_QA_RUN_DIR:-/tmp/flowai-manual-qa})
#     mq::state_init              — validate the root path, create the protected tree
#     mq::state_path <rel>        — absolute path inside the runtime state dir
#     mq::state_write_env         — write a key=value line to state/env.sh with %q
#     mq::state_require_env       — verify owner/mode and source state/env.sh
#
#   Certificate issuance (OpenSSL, ephemeral CA, GNU `timeout`-bounded)
#     mq::openssl_run <args...>   — run openssl under `timeout` with a stdout cap
#     mq::ca_init                 — generate a private CA
#     mq::issue_server_cert       — issue a localhost+127.0.0.1 serverAuth cert
#     mq::issue_client_cert       — issue a clientAuth cert with role/team/serial subject
#
#   Backend HTTP curl wrappers
#     mq::curl_http_json          — GET/POST/PUT JSON over backend HTTP
#     mq::curl_admin_post         — POST /admin/* with trusted admin context
#     mq::curl_listener_post      — POST /v1/tasks with listener context
#     mq::curl_gateway_get        — GET with trusted Gateway context
#
#   JSON helpers
#     mq::json_encode             — emit a JSON object via jq (--argjson for JSON, --arg for strings)
#     mq::jq_available            — return 0 when jq is on PATH
#
#   Plain HTTP wait helper (the executor binds 127.0.0.1:8020 plaintext)
#     mq::wait_http_plain
#
#   Container runtime helpers (Podman only)
#     mq::detect_runtime          — print 'podman' or fail
#     mq::runtime_run_postgres    — start a TLS-enabled Postgres 16 container, loopback-only, :Z
#     mq::runtime_remove          — remove a container by id (best-effort, idempotent)
#     mq::runtime_stage_pg_tls    — write the staged cert + key + custom entrypoint
#     mq::random_password         — 16 random bytes / 32 hex characters
#
#   Process supervision
#     mq::pid_is_alive            — return 0 when the pid is running
#     mq::pid_identity_check      — refuse to act on a PID whose cmdline does not match
#     mq::terminate_pid           — SIGTERM (with identity check) then SIGKILL
#
#   Wait helpers
#     mq::wait_http_plain         — wait for a plaintext http endpoint to respond
#
# Security boundaries enforced here:
#   * runtime state dir is mode 0700; every state file is mode 0600
#   * private keys are mode 0600 by construction
#   * runtime state is generated by THIS script only; nothing is sourced
#     from an attacker-controlled arbitrary path; the env export file is
#     owner-checked + mode-checked before being sourced
#   * the env export file is emitted through Bash %q so values never
#     become shell-active (no eval)
#   * no curl -k, no InsecureSkipVerify, no plaintext fallback for the
#     State Registry surfaces
#   * openssl subprocesses are bounded by GNU `timeout` and an output cap
#   * process termination is gated on a /proc/PID/cmdline check so a
#     stale PID file cannot cause a wrong process to be killed

# --- strict mode -----------------------------------------------------------

mq::enter_strict_mode() {
  set -o errexit
  set -o pipefail
  set -o nounset
  set -o errtrace
  # Owner-only default. Every file this script creates uses install -m
  # explicitly; umask 0077 is defense in depth.
  umask 0077
  IFS=$' \t\n'
}

mq::trace() {
  # mq::trace <phase> <message>
  printf '[%s] [%s] %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "${1:-run}" "${2:-}" >&2
}

mq::fail() {
  # mq::fail <message>
  mq::trace "fatal" "${1:-unspecified failure}"
  exit 1
}

mq::require_cmd() {
  local cmd="${1:-}"
  if [[ -z "$cmd" ]]; then
    mq::fail "mq::require_cmd called without an argument"
  fi
  if ! command -v "$cmd" >/dev/null 2>&1; then
    mq::fail "required command not found on PATH: $cmd"
  fi
}

mq::require_rootless_podman() {
  local uid
  uid="$(id -u)"
  local runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$uid}"
  local sock="$runtime_dir/podman/podman.sock"
  if [[ ! -S "$sock" ]]; then
    mq::fail "rootless Podman socket not found at $sock (XDG_RUNTIME_DIR=$runtime_dir); enable with 'systemctl --user enable --now podman.socket' or set XDG_RUNTIME_DIR"
  fi
  local owner_uid
  owner_uid="$(stat -c '%u' "$sock" 2>/dev/null || true)"
  if [[ "$owner_uid" != "$uid" ]]; then
    mq::fail "rootless Podman socket at $sock is owned by uid=$owner_uid, expected $uid"
  fi
}

# --- local dotenv loader (NO source / NO eval) ---------------------------

# mq::load_dotenv <path>
# Parse a simple KEY=VALUE dotenv file into the current shell.
#
# Hard requirements (enforced):
#   * NEVER sources the file; NEVER evals it; NEVER uses `set -a`.
#   * Refuses symlink files.
#   * Refuses non-current-owner files.
#   * Refuses any mode that grants group / world access (must be 0600
#     or 0400; 0600 is the canonical mode for manual-qa/.env).
#   * Refuses files containing NUL bytes (binary content rejected).
#   * Refuses lines with carriage returns (CR).
#   * Refuses malformed lines, unknown keys, and invalid identifiers.
#   * Refuses values containing $ / ` / \ in unquoted form (no
#     parameter / command expansion).
#   * Refuses trailing junk after a closing quote.
#
# Supported value forms:
#   * unquoted literal (no shell metacharacters allowed)
#   * single-quoted literal '...'   (no expansion inside)
#   * double-quoted literal "..."   (no expansion inside)
#   * empty unquoted / empty quoted value
#
# Precedence: a shell variable that is already set (whether exported
# from the parent environment or assigned earlier in the script) takes
# precedence over the .env file. An explicitly empty exported variable
# is detected via `${var+X}` and is also honoured as a precedence win.
mq::load_dotenv() {
  local path="${1:-}"
  [[ -n "$path" ]] || mq::fail "mq::load_dotenv requires a path"

  if [[ ! -e "$path" ]]; then
    mq::fail "mq::load_dotenv: $path does not exist"
  fi
  if [[ -L "$path" ]]; then
    mq::fail "mq::load_dotenv: $path is a symlink; refusing to parse"
  fi
  if [[ ! -f "$path" ]]; then
    mq::fail "mq::load_dotenv: $path is not a regular file"
  fi

  local my_uid owner_uid mode
  my_uid="$(id -u)"
  owner_uid="$(stat -c '%u' "$path" 2>/dev/null || true)"
  mode="$(stat -c '%a' "$path" 2>/dev/null || true)"
  if [[ -z "$owner_uid" || -z "$mode" ]]; then
    mq::fail "mq::load_dotenv: stat failed for $path"
  fi
  if [[ "$owner_uid" != "$my_uid" ]]; then
    mq::fail "mq::load_dotenv: $path is owned by uid=$owner_uid, expected $my_uid"
  fi
  case "$mode" in
    600|400) ;;
    *) mq::fail "mq::load_dotenv: $path has mode=$mode (must be 0600 or 0400); group/world-writable refused" ;;
  esac

  # NUL bytes cannot appear in a well-formed dotenv file. Reject them
  # up front so a hostile value cannot smuggle binary content past the
  # line-based reader. The implementation translates NULs to '@' with
  # tr and then greps for '@' — a NUL-terminated C-string trick used
  # by grep -F cannot match an empty pattern and would otherwise
  # produce a false positive on every clean text file.
  if LC_ALL=C tr '\0' '@' <"$path" | grep -q '@'; then
    mq::fail "mq::load_dotenv: $path contains NUL bytes (binary content rejected)"
  fi

  local lineno=0 raw key value stripped
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    lineno=$((lineno + 1))

    # Reject Windows-style line endings (the read above would have
    # preserved the trailing CR inside `raw`).
    if [[ "$raw" == *$'\r'* ]]; then
      mq::fail "mq::load_dotenv: $path:$lineno contains carriage return (Windows line endings rejected)"
    fi

    # Strip leading whitespace only; trailing whitespace on a data line
    # is rejected as malformed because real whitespace inside an
    # unquoted value is ambiguous.
    stripped="${raw#"${raw%%[![:space:]]*}"}"

    # Blank line or full-line comment.
    if [[ -z "$stripped" ]]; then
      continue
    fi
    if [[ "$stripped" == \#* ]]; then
      continue
    fi

    if [[ ! "$raw" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      mq::fail "mq::load_dotenv: $path:$lineno malformed line (expected KEY=VALUE): $raw"
    fi
    key="${BASH_REMATCH[1]}"
    value="${BASH_REMATCH[2]}"

    # Fixed allow-list. Anything else is a hard error.
    case "$key" in
      OPENHANDS_LLM_MODEL|OPENHANDS_LLM_API_KEY|OPENHANDS_LLM_USAGE_ID|\
OPENHANDS_LLM_BASE_URL|OPENHANDS_AGENT_PROFILE_ID|PROMPT|\
FLOWAI_MANUAL_QA_RUN_DIR|FLOWAI_REPO_ROOT|DOCKER_SOCKET_PATH|\
OPENHANDS_HOST_PORT_START|OPENHANDS_HOST_PORT_END|OPENHANDS_WORKSPACE|\
RUN_ALL_NO_CLEANUP)
        ;;
      *) mq::fail "mq::load_dotenv: $path:$lineno unknown key '$key' (not in allow-list)" ;;
    esac

    # Parse the value form. Inside single / double quotes the content
    # is purely literal; no $, no `, no \ escape processing.
    case "$value" in
      \"\")
        value=""
        ;;
      \"*)
        if [[ "${#value}" -lt 2 || "$value" != *'"'* ]]; then
          mq::fail "mq::load_dotenv: $path:$lineno unterminated double quote"
        fi
        if [[ "${value: -1}" != '"' ]]; then
          mq::fail "mq::load_dotenv: $path:$lineno trailing junk after double quote"
        fi
        value="${value:1:-1}"
        ;;
      \'\')
        value=""
        ;;
      \'*)
        if [[ "${#value}" -lt 2 || "$value" != *\'* ]]; then
          mq::fail "mq::load_dotenv: $path:$lineno unterminated single quote"
        fi
        if [[ "${value: -1}" != \' ]]; then
          mq::fail "mq::load_dotenv: $path:$lineno trailing junk after single quote"
        fi
        value="${value:1:-1}"
        ;;
      *)
        # Unquoted literal. Reject any character that could enable
        # parameter / command expansion or backslash escape.
        if [[ "$value" == *\$\(* || "$value" == *\$\{* || "$value" == *\`* || "$value" == *\\* ]]; then
          mq::fail "mq::load_dotenv: $path:$lineno unquoted value contains expansion or escape character"
        fi
        ;;
    esac

    # Precedence: anything already set in this shell wins, including
    # explicitly empty exported variables. We must use indirect
    # expansion (${!key+X}) so the check tests the variable *named by*
    # $key — a plain ${key+X} would test the local variable `key`
    # itself, which is always set inside this function and would mask
    # every .env value.
    if [[ -n "${!key+X}" ]]; then
      continue
    fi

    # Export so the value is visible to child processes started by the
    # operational scripts (Executor, State Registry, Postgres).
    export "$key=$value"
  done < "$path"
}

# mq::load_manual_qa_dotenv <script-dir>
# Convenience wrapper: load <script-dir>/.env into the current shell
# when the file exists. Quietly does nothing when the file is absent
# so callers can invoke this unconditionally.
mq::load_manual_qa_dotenv() {
  local script_dir="${1:-}"
  [[ -n "$script_dir" ]] || mq::fail "mq::load_manual_qa_dotenv requires a script directory"
  local dotenv_file="$script_dir/.env"
  if [[ -f "$dotenv_file" && ! -L "$dotenv_file" ]]; then
    mq::load_dotenv "$dotenv_file"
  fi
}

# --- runtime state --------------------------------------------------------

mq::state_init() {
  # An unset or empty value intentionally uses the documented default.
  if [[ -z "${FLOWAI_MANUAL_QA_RUN_DIR:-}" ]]; then
    FLOWAI_MANUAL_QA_RUN_DIR="/tmp/flowai-manual-qa"
  fi

  # Validate the selected root path. We refuse:
  #   - "/"
  #   - exact '.' or '..' path segments (which could traverse unexpectedly)
  #   - symlink at the root (would let a hostile symlink redirect all
  #     later file writes outside the chosen root)
  if [[ "$FLOWAI_MANUAL_QA_RUN_DIR" == "/" ]]; then
    mq::fail "FLOWAI_MANUAL_QA_RUN_DIR must be a non-root directory; got '$FLOWAI_MANUAL_QA_RUN_DIR'"
  fi
  case "/$FLOWAI_MANUAL_QA_RUN_DIR/" in
    */./*|*/../*) mq::fail "FLOWAI_MANUAL_QA_RUN_DIR contains a traversal segment: $FLOWAI_MANUAL_QA_RUN_DIR" ;;
  esac
  if [[ -L "$FLOWAI_MANUAL_QA_RUN_DIR" ]]; then
    mq::fail "FLOWAI_MANUAL_QA_RUN_DIR is a symlink: $FLOWAI_MANUAL_QA_RUN_DIR (refusing to follow)"
  fi
  export FLOWAI_MANUAL_QA_RUN_DIR

  if [[ ! -d "$FLOWAI_MANUAL_QA_RUN_DIR" ]]; then
    install -d -m 0700 "$FLOWAI_MANUAL_QA_RUN_DIR" || mq::fail "create $FLOWAI_MANUAL_QA_RUN_DIR"
  fi
  # Tighten permissions on every entry (covers re-runs into a previous dir).
  chmod 0700 "$FLOWAI_MANUAL_QA_RUN_DIR"

  local sub
  for sub in state certs logs pids bin pg-tls; do
    if [[ -L "$FLOWAI_MANUAL_QA_RUN_DIR/$sub" ]]; then
      mq::fail "runtime state subdirectory is a symlink: $FLOWAI_MANUAL_QA_RUN_DIR/$sub (refusing to follow)"
    fi
    install -d -m 0700 "$FLOWAI_MANUAL_QA_RUN_DIR/$sub" \
      || mq::fail "create $FLOWAI_MANUAL_QA_RUN_DIR/$sub"
  done
}

mq::state_path() {
  # mq::state_path <relative-path>
  local rel="${1:-}"
  [[ -n "$rel" ]] || mq::fail "mq::state_path requires a relative path"
  # Reject absolute paths or exact '.' / '..' segments that could escape
  # or ambiguously resolve within the runtime root.
  case "$rel" in
    /*) mq::fail "mq::state_path: relative path must not be absolute: $rel" ;;
  esac
  case "/$rel/" in
    */./*|*/../*) mq::fail "mq::state_path: relative path must not contain '.' or '..' segments: $rel" ;;
  esac
  printf '%s/%s\n' "${FLOWAI_MANUAL_QA_RUN_DIR:?}" "$rel"
}

mq::state_write_env() {
  # mq::state_write_env <key> <value>
  # The key MUST be a valid shell identifier; the value is emitted via
  # Bash %q so a hostile value cannot become a shell command. The
  # resulting file is mode 0600, owned by the current user, and is
  # the ONLY path other scripts ever source.
  local key="${1:-}"
  local value="${2:-}"
  [[ -n "$key" ]] || mq::fail "mq::state_write_env requires a key"
  if [[ ! "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    mq::fail "mq::state_write_env: '$key' is not a valid shell identifier"
  fi

  local env_file
  env_file="$(mq::state_path state/env.sh)"
  local tmp
  tmp="$(mktemp "$(mq::state_path state)/env.sh.XXXXXX")"
  chmod 0600 "$tmp"
  if [[ -f "$env_file" ]]; then
    # grep returns 1 normally when no previous declaration for this key exists.
    grep -v -E "^declare -g ${key}=" "$env_file" >"$tmp" || true
  fi
  printf 'declare -g %s=%q\n' "$key" "$value" >>"$tmp"
  mv -f "$tmp" "$env_file"
  chmod 0600 "$env_file"
}

mq::state_require_env() {
  local env_file
  env_file="$(mq::state_path state/env.sh)"
  if [[ ! -f "$env_file" ]]; then
    mq::fail "runtime env file missing at $env_file; run 01-prepare.sh first"
  fi
  if [[ -L "$env_file" ]]; then
    mq::fail "$env_file is a symlink; refusing to source"
  fi
  local owner_uid mode my_uid
  owner_uid="$(stat -c '%u' "$env_file" 2>/dev/null || true)"
  mode="$(stat -c '%a' "$env_file" 2>/dev/null || true)"
  my_uid="$(id -u)"
  if [[ "$owner_uid" != "$my_uid" ]]; then
    mq::fail "$env_file is owned by uid=$owner_uid, expected $my_uid"
  fi
  if [[ "$mode" != "600" ]]; then
    mq::fail "$env_file has mode=$mode (must be 0600)"
  fi
  # shellcheck disable=SC1090
  source "$env_file"
}

# --- certificate issuance (GNU timeout-bounded) ---------------------------

MQ_OPENSSL_DEADLINE_MS="${MQ_OPENSSL_DEADLINE_MS:-15000}"
MQ_OPENSSL_OUTPUT_CAP_BYTES="${MQ_OPENSSL_OUTPUT_CAP_BYTES:-16384}"

mq::openssl_run() {
  # mq::openssl_run <args...>
  local -a args=("$@")
  local bin
  bin="$(command -v openssl || true)"
  [[ -n "$bin" ]] || mq::fail "openssl binary not found on PATH"
  command -v timeout >/dev/null 2>&1 || mq::fail "GNU 'timeout' is required by mq::openssl_run but was not found on PATH"

  local stdout_tmp stderr_tmp
  stdout_tmp="$(mktemp)" || mq::fail "mktemp stdout"
  stderr_tmp="$(mktemp)" || mq::fail "mktemp stderr"
  chmod 0600 "$stdout_tmp" "$stderr_tmp"

  # timeout sends SIGTERM at the deadline and escalates to SIGKILL after
  # an additional grace window so a stuck openssl can never hang the
  # whole QA flow. GNU timeout accepts only s/m/h/d units, so convert
  # the millisecond cap to whole seconds (rounded up to at least 1s).
  local deadline_s
  deadline_s="$(( (MQ_OPENSSL_DEADLINE_MS + 999) / 1000 ))"
  [[ "$deadline_s" -ge 1 ]] || deadline_s=1

  set +o errexit
  timeout --kill-after=2 "${deadline_s}s" "$bin" "${args[@]}" \
    >"$stdout_tmp" 2>"$stderr_tmp"
  local rc=$?
  set -o errexit

  if [[ $rc -ne 0 ]]; then
    local stderr_trimmed
    stderr_trimmed="$(head -c 4096 "$stderr_tmp")"
    rm -f "$stdout_tmp" "$stderr_tmp"
    mq::fail "openssl ${args[*]} exited code=$rc stderr=$stderr_trimmed"
  fi
  local out_bytes
  out_bytes="$(wc -c <"$stdout_tmp")"
  if (( out_bytes > MQ_OPENSSL_OUTPUT_CAP_BYTES )); then
    : >"$stdout_tmp"
  fi
  cat "$stdout_tmp"
  rm -f "$stdout_tmp" "$stderr_tmp"
}

mq::ca_init() {
  # mq::ca_init <ca-dir>
  local dir="${1:-}"
  [[ -n "$dir" ]] || mq::fail "mq::ca_init requires a directory"
  install -d -m 0700 "$dir" || mq::fail "mkdir $dir"

  mq::openssl_run genrsa -out "$dir/ca.key" 2048 >/dev/null
  chmod 0600 "$dir/ca.key"

  mq::openssl_run req -x509 -new -batch \
    -key "$dir/ca.key" \
    -out "$dir/ca.crt" \
    -days 1 \
    -subj "/CN=flowai-manual-qa-ca/OU=qa" >/dev/null
  chmod 0644 "$dir/ca.crt"
}

mq::openssl_server_ext() {
  cat <<'EOF'
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
EOF
}

mq::openssl_client_ext() {
  cat <<'EOF'
extendedKeyUsage = clientAuth
EOF
}

# Build a Bash-quoted /N=v1/N=v2/... subject line from key=value pairs.
# Empty values are skipped (so admin gets no O=, no serialNumber=).
mq::build_subject() {
  local -a parts=()
  local kv
  for kv in "$@"; do
    [[ -n "$kv" ]] || continue
    local key="${kv%%=*}"
    local val="${kv#*=}"
    [[ -n "$val" ]] || continue
    parts+=("/${key}=${val}")
  done
  local IFS=
  printf '%s' "${parts[*]}"
}

mq::issue_server_cert() {
  # mq::issue_server_cert <ca-dir> <out-dir> <name>
  local ca_dir="${1:-}" out_dir="${2:-}" name="${3:-server}"
  [[ -n "$ca_dir" && -n "$out_dir" && -n "$name" ]] || mq::fail "issue_server_cert args"

  install -d -m 0700 "$out_dir" || mq::fail "mkdir $out_dir"

  mq::openssl_run genrsa -out "$out_dir/$name.key" 2048 >/dev/null
  chmod 0600 "$out_dir/$name.key"

  mq::openssl_run req -new -batch \
    -key "$out_dir/$name.key" \
    -out "$out_dir/$name.csr" \
    -subj "/CN=flowai-manual-qa-$name/OU=qa" >/dev/null

  local ext="$out_dir/$name.ext"
  mq::openssl_server_ext >"$ext"
  chmod 0600 "$ext"

  mq::openssl_run x509 -req \
    -in "$out_dir/$name.csr" \
    -CA "$ca_dir/ca.crt" \
    -CAkey "$ca_dir/ca.key" \
    -CAcreateserial \
    -out "$out_dir/$name.crt" \
    -days 1 \
    -extfile "$ext" >/dev/null
  chmod 0644 "$out_dir/$name.crt"
  rm -f "$out_dir/$name.csr"
}

mq::issue_client_cert() {
  # mq::issue_client_cert <ca-dir> <out-dir> <name> <subject-kv...>
  local ca_dir="${1:-}" out_dir="${2:-}" name="${3:-}"
  shift 3
  [[ -n "$ca_dir" && -n "$out_dir" && -n "$name" ]] || mq::fail "issue_client_cert args"

  install -d -m 0700 "$out_dir" || mq::fail "mkdir $out_dir"

  mq::openssl_run genrsa -out "$out_dir/$name.key" 2048 >/dev/null
  chmod 0600 "$out_dir/$name.key"

  local subject
  subject="$(mq::build_subject "$@")"

  mq::openssl_run req -new -batch \
    -key "$out_dir/$name.key" \
    -out "$out_dir/$name.csr" \
    -subj "$subject" >/dev/null

  local ext="$out_dir/$name.ext"
  mq::openssl_client_ext >"$ext"
  chmod 0600 "$ext"

  mq::openssl_run x509 -req \
    -in "$out_dir/$name.csr" \
    -CA "$ca_dir/ca.crt" \
    -CAkey "$ca_dir/ca.key" \
    -CAcreateserial \
    -out "$out_dir/$name.crt" \
    -days 1 \
    -extfile "$ext" >/dev/null
  chmod 0644 "$out_dir/$name.crt"
  rm -f "$out_dir/$name.csr"
}

# --- backend HTTP curl wrappers ------------------------------------------

mq::curl_http_json() {
  # mq::curl_http_json <method> <url> <body-file-or-empty> [header ...]
  # Prints "<HTTP_STATUS>\n<body>" on stdout. Uses --fail-with-body so a
  # non-2xx response is surfaced as an explicit error rather than a
  # silent empty body. The caller must never pass -k / insecure.
  local method="${1:-GET}" url="${2:-}" body="${3:-}"
  shift 3
  [[ -n "$url" ]] || mq::fail "curl_http_json: url is required"

  local -a curl_args=(
    --silent
    --show-error
    --fail-with-body
    --request "$method"
    --url "$url"
    --connect-timeout 5
    --max-time 30
    --write-out '\n%{http_code}'
    --header 'Accept: application/json'
  )
  local header
  for header in "$@"; do
    curl_args+=(--header "$header")
  done
  if [[ -n "$body" ]]; then
    curl_args+=(--header 'Content-Type: application/json' --data-binary "@$body")
  fi

  local resp status
  resp="$(curl "${curl_args[@]}")"
  status="${resp##*$'\n'}"
  body="${resp%$'\n'*}"
  printf '%s\n%s' "$status" "$body"
}

mq::curl_admin_post() {
  # mq::curl_admin_post <url> <body-file>
  mq::curl_http_json POST "$1" "$2" \
    "X-FlowAI-Role: admin" \
    "X-FlowAI-Admin-Subject: system-admin-local" \
    "X-FlowAI-Request-Id: manual-admin-$RANDOM"
}

mq::curl_listener_post() {
  # mq::curl_listener_post <url> <body-file>
  mq::curl_http_json POST "$1" "$2" \
    "X-FlowAI-Role: listener" \
    "X-FlowAI-Team-Id: $FLOWAI_TEAM_ID" \
    "X-FlowAI-Source-System-Id: $FLOWAI_SOURCE_SYSTEM_ID" \
    "X-FlowAI-Listener-Identity: listener-local" \
    "X-FlowAI-Request-Id: manual-listener-$RANDOM"
}

mq::curl_gateway_get() {
  # mq::curl_gateway_get <url>
  mq::curl_http_json GET "$1" "" \
    "X-FlowAI-Role: gateway" \
    "X-FlowAI-Team-Id: $FLOWAI_TEAM_ID" \
    "X-FlowAI-Operator-Id: operator-local" \
    "X-FlowAI-Request-Id: manual-gateway-$RANDOM"
}

# --- JSON encoding --------------------------------------------------------

mq::jq_available() {
  command -v jq >/dev/null 2>&1
}

# Detect whether a value is already valid JSON (object / array / string /
# number / bool / null). Used by mq::json_encode to pick --argjson vs
# --arg so nested objects survive intact.
mq::json_value_is_json() {
  local val="${1:-}"
  case "$val" in
    true|false|null) return 0 ;;
  esac
  if [[ "$val" =~ ^-?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$ ]]; then
    return 0
  fi
  case "$val" in
    \"*) return 0 ;; # already a JSON-quoted string
  esac
  case "$val" in
    \{*\}|\[*\]|\{*|\[*)
      # Object or array literal; verify with python (jq is unavailable
      # at this layer when this helper is invoked).
      python3 -c "import json,sys; json.loads(sys.argv[1])" "$val" >/dev/null 2>&1
      return $?
      ;;
  esac
  return 1
}

mq::json_encode() {
  # mq::json_encode <key=value>...
  # Emits a single JSON object on stdout. Each value that is already
  # valid JSON is passed through with --argjson; everything else is
  # passed with --arg so jq's safe-string quoting applies.
  local -a jq_args=()
  local -a py_kvs=()
  local kv key val

  for kv in "$@"; do
    key="${kv%%=*}"
    val="${kv#*=}"
    if mq::jq_available; then
      if mq::json_value_is_json "$val"; then
        jq_args+=(--argjson "$key" "$val")
      else
        jq_args+=(--arg "$key" "$val")
      fi
    else
      py_kvs+=("$kv")
    fi
  done

  if mq::jq_available; then
    jq -n '$ARGS.named' "${jq_args[@]}" 2>/dev/null || mq::fail "jq encode"
    return 0
  fi

  # python3 fallback — same contract; values are validated with
  # json.loads so nested objects survive intact.
  python3 - "${py_kvs[@]}" <<'PY' || mq::fail "python3 encode"
import json, sys
out = {}
for kv in sys.argv[1:]:
    if "=" not in kv:
        print(f"bad kv: {kv}", file=sys.stderr); sys.exit(2)
    k, v = kv.split("=", 1)
    try:
        out[k] = json.loads(v)
    except Exception:
        out[k] = v
print(json.dumps(out, separators=(",", ":")))
PY
}

# --- container runtime ----------------------------------------------------

# Podman only. The manual QA flow requires rootless Podman.
mq::detect_runtime() {
  if command -v podman >/dev/null 2>&1; then
    printf 'podman\n'
    return 0
  fi
  mq::fail "podman is required on PATH; this manual QA flow does not support Docker"
}

# Run a runtime subprocess with bounded stdout/stderr. We never eval the
# command; every arg is array-passed.
mq::runtime_spawn() {
  local rt="${1:-}"
  shift
  [[ -n "$rt" ]] || mq::fail "runtime_spawn: runtime is required"
  local stdout_tmp stderr_tmp
  stdout_tmp="$(mktemp)" || mq::fail "mktemp stdout"
  stderr_tmp="$(mktemp)" || mq::fail "mktemp stderr"
  chmod 0600 "$stdout_tmp" "$stderr_tmp"

  set +o errexit
  "$rt" "$@" >"$stdout_tmp" 2>"$stderr_tmp"
  local rc=$?
  set -o errexit
  if [[ $rc -ne 0 ]]; then
    local stderr_trimmed
    stderr_trimmed="$(head -c 4096 "$stderr_tmp")"
    rm -f "$stdout_tmp" "$stderr_tmp"
    mq::fail "$rt $* exited code=$rc stderr=$stderr_trimmed"
  fi
  cat "$stdout_tmp"
  rm -f "$stdout_tmp" "$stderr_tmp"
}

# Generate a fresh postgres password from 16 random bytes / 32 hex characters;
# no quoted/escaped values leak into the env file because the runtime puts it
# on the command line with --env KEY=value (no shell).
mq::random_password() {
  head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
}

mq::runtime_run_postgres() {
  # mq::runtime_run_postgres <runtime> <name> <password> <db>
  # Starts a TLS-enabled postgres:16 with loopback-only publication,
  # a tmpfs data directory, and SELinux-safe :Z bind mounts. Persists
  # the container id, the host port, and the container name so cleanup
  # can find the artifact even after this function returns.
  local rt="${1:-}" name="${2:-}" password="${3:-}" db="${4:-flowai}"
  [[ -n "$rt" && -n "$name" && -n "$password" && -n "$db" ]] \
    || mq::fail "runtime_run_postgres args"

  local tls_dir
  tls_dir="$(mq::state_path state/pg-tls)"
  install -d -m 0700 "$tls_dir" || mq::fail "mkdir pg-tls"

  mq::runtime_stage_pg_tls "$tls_dir"

  # Invoke the staged entrypoint through /bin/bash. The whole tls-dir
  # is mounted as one private SELinux volume (:ro,Z); the entrypoint
  # path inside the container is /etc/flowai/pg-tls/custom-entrypoint.sh.
  local cid
  cid="$(mq::runtime_spawn "$rt" run \
    --detach \
    --rm \
    --name "$name" \
    --publish "127.0.0.1::5432" \
    --tmpfs "/var/lib/postgresql/data:rw" \
    --volume "$tls_dir:/etc/flowai/pg-tls:ro,Z" \
    --entrypoint /bin/bash \
    --env "POSTGRES_PASSWORD=$password" \
    --env "POSTGRES_DB=$db" \
    docker.io/library/postgres:16 \
    /etc/flowai/pg-tls/custom-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
  )" || mq::fail "postgres run"
  cid="${cid//[[:space:]]/}"
  printf '%s\n' "$cid" > "$(mq::state_path state/pg.cid)"
  chmod 0600 "$(mq::state_path state/pg.cid)"
  printf '%s\n' "$name" > "$(mq::state_path state/pg.name)"
  chmod 0600 "$(mq::state_path state/pg.name)"

  local host_port=""
  local deadline=$(( $(date +%s) + 30 ))
  while [[ $(date +%s) -lt $deadline ]]; do
    local out inspect_rc
    set +o errexit
    out="$("$rt" inspect \
      --format '{{(index (index .NetworkSettings.Ports "5432/tcp") 0).HostPort}}' \
      "$cid" 2>/dev/null)"
    inspect_rc=$?
    set -o errexit
    if [[ $inspect_rc -eq 0 && "$out" =~ ^[0-9]+$ ]] && [[ "$out" -gt 0 ]]; then
      host_port="$out"
      break
    fi
    sleep 0.2
  done
  [[ -n "$host_port" ]] || mq::fail "postgres: OS-assigned host port never resolved for container $cid"
  printf '%s\n' "$host_port" > "$(mq::state_path state/pg.host_port)"
  chmod 0600 "$(mq::state_path state/pg.host_port)"
  printf '%s\n%s\n' "$cid" "$host_port"
}

mq::runtime_stage_pg_tls() {
  # mq::runtime_stage_pg_tls <tls-dir>
  # Copies the cert + key from the runtime state certs dir into tls-dir
  # and writes a custom entrypoint that copies them into
  # /var/lib/postgresql/ with postgres:postgres ownership and 0600/0644
  # mode, then execs the original docker-entrypoint.sh.
  local dir="${1:-}"
  [[ -n "$dir" ]] || mq::fail "runtime_stage_pg_tls requires a directory"
  install -d -m 0700 "$dir"

  cp -f "$(mq::state_path state/certs/pg-server.crt)" "$dir/server.crt"
  cp -f "$(mq::state_path state/certs/pg-server.key)" "$dir/server.key"
  chmod 0644 "$dir/server.crt"
  chmod 0600 "$dir/server.key"

  cat >"$dir/custom-entrypoint.sh" <<'ENTRYPOINT'
#!/bin/bash
set -eu
SRC_DIR="/etc/flowai/pg-tls"
DST_CERT="/var/lib/postgresql/server.crt"
DST_KEY="/var/lib/postgresql/server.key"
cp -f "${SRC_DIR}/server.crt" "${DST_CERT}"
cp -f "${SRC_DIR}/server.key" "${DST_KEY}"
chown postgres:postgres "${DST_CERT}" "${DST_KEY}"
chmod 0644 "${DST_CERT}"
chmod 0600 "${DST_KEY}"
exec /usr/local/bin/docker-entrypoint.sh "$@"
ENTRYPOINT
  chmod 0755 "$dir/custom-entrypoint.sh"
}

mq::runtime_remove() {
  # mq::runtime_remove <runtime> <container-id>
  local rt="${1:-}" cid="${2:-}"
  [[ -n "$rt" && -n "$cid" ]] || mq::fail "runtime_remove args"
  set +o errexit
  "$rt" rm --force "$cid" >/dev/null 2>&1 || true
  set -o errexit
}

# --- process supervision --------------------------------------------------

mq::pid_is_alive() {
  local pid="${1:-}"
  [[ -n "$pid" ]] || return 1
  kill -0 "$pid" 2>/dev/null
}

# mq::pid_identity_check <pid> <expected-binary-substring>
# Returns 0 when the pid's /proc/PID/cmdline contains the expected
# binary substring. Used to refuse to terminate a process whose PID
# has been reused for a different executable.
mq::pid_identity_check() {
  local pid="${1:-}" expected="${2:-}"
  [[ -n "$pid" && -n "$expected" ]] || return 1
  [[ -r "/proc/$pid/cmdline" ]] || return 1
  local cmdline
  cmdline="$(tr '\0' ' ' <"/proc/$pid/cmdline" 2>/dev/null || true)"
  [[ "$cmdline" == *"$expected"* ]]
}

mq::terminate_pid() {
  # mq::terminate_pid <pid> <timeout-seconds> <expected-binary-substring>
  # Refuses to signal a process whose /proc/PID/cmdline does not match
  # the expected binary substring.
  local pid="${1:-}" timeout_s="${2:-10}" expected="${3:-}"
  [[ -n "$pid" ]] || mq::fail "terminate_pid requires a pid"
  if ! mq::pid_is_alive "$pid"; then
    return 0
  fi
  if [[ -n "$expected" ]] && ! mq::pid_identity_check "$pid" "$expected"; then
    mq::fail "pid=$pid cmdline does not match expected '$expected'; refusing to kill (likely PID reuse)"
  fi
  set +o errexit
  kill -TERM "$pid" 2>/dev/null || true
  local end=$(( $(date +%s) + timeout_s ))
  while [[ $(date +%s) -lt $end ]]; do
    if ! mq::pid_is_alive "$pid"; then
      set -o errexit
      return 0
    fi
    sleep 0.2
  done
  kill -KILL "$pid" 2>/dev/null || true
  sleep 0.5
  if mq::pid_is_alive "$pid"; then
    set -o errexit
    mq::fail "process pid=$pid refused to exit within ${timeout_s}s after SIGTERM + SIGKILL"
  fi
  set -o errexit
}

# --- wait helpers ---------------------------------------------------------

mq::wait_http_https() {
  # mq::wait_http_https <url> <cacert> <cert> <key> <timeout-seconds>
  local url="${1:-}" cacert="${2:-}" cert="${3:-}" key="${4:-}" timeout_s="${5:-30}"
  local end=$(( $(date +%s) + timeout_s ))
  local last_err=""
  while [[ $(date +%s) -lt $end ]]; do
    local out
    set +o errexit
    out="$(curl --silent --show-error --fail-with-body \
      --cacert "$cacert" --cert "$cert" --key "$key" \
      --max-time 3 "$url" 2>&1)"
    local rc=$?
    set -o errexit
    if [[ $rc -eq 0 ]]; then
      printf '%s\n' "$out"
      return 0
    fi
    last_err="$out"
    sleep 0.5
  done
  mq::fail "wait_http_https: $url never responded within ${timeout_s}s (last error: ${last_err:0:256})"
}

mq::wait_http_plain() {
  # mq::wait_http_plain <url> <timeout-seconds>
  # Plaintext wait helper used to probe the executor's own platform
  # health surface, which is intentionally plaintext (the executor
  # binds 127.0.0.1:8020 without TLS; mTLS is reserved for the State
  # Registry). Uses --fail-with-body so an HTTP 4xx/5xx response is
  # treated as not-ready rather than silently accepted.
  local url="${1:-}" timeout_s="${2:-30}"
  local end=$(( $(date +%s) + timeout_s ))
  local last_err=""
  while [[ $(date +%s) -lt $end ]]; do
    local out
    set +o errexit
    out="$(curl --silent --show-error --fail-with-body --max-time 3 "$url" 2>&1)"
    local rc=$?
    set -o errexit
    if [[ $rc -eq 0 ]]; then
      printf '%s\n' "$out"
      return 0
    fi
    last_err="$out"
    sleep 0.5
  done
  mq::fail "wait_http_plain: $url never responded within ${timeout_s}s (last error: ${last_err:0:256})"
}
