packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: set this to true or false

onlyBuiltDependencies:
  - 'esbuild'
  - '@parcel/watcher'
  - 'better-sqlite3'
  - 'core-js'
  - 'core-js-pure'
