// Permission + cleanup contract for fixtures/tls_transport.ts.
//
// The contract is:
//   1. Every private key generated by createEphemeralTlsMaterial is
//      mode 0600 on disk (owner read/write only).
//   2. Every key-bearing temp directory is mode 0700 on disk
//      (owner access only).
//   3. Public certs remain readable (>= 0644) so TLS clients can
//      load them without altering the file mode.
//   4. cleanup() is idempotent: calling it twice in a row never
//      throws and never resolves with a rejected promise.
//   5. cleanup() propagates a real removal failure: a directory
//      whose contents cannot be removed (because the parent
//      directory is locked down to mode 0500) makes cleanup()
//      reject with the underlying error rather than swallow it.
//
// The tests never log key bytes, cert bytes, or DSNs.

import { test, expect } from "@playwright/test";
import { statSync, chmodSync } from "node:fs";
import { join, resolve as pathResolve } from "node:path";
import {
  createEphemeralTlsMaterial,
  type EphemeralTlsMaterial,
} from "../fixtures/tls_transport";

// modeOf returns the octal mode of a path. Uses statSync (sync) so
// the test can assert immediately after the fixture finishes
// generating the material without race-prone polling.
function modeOf(path: string): number {
  return statSync(path).mode & 0o777;
}

test.describe("createEphemeralTlsMaterial permission + cleanup contract", () => {
  // The material is expensive to generate (it spawns openssl
  // multiple times). Generate one bundle and share it across the
  // permission assertions; the idempotency / propagation tests use
  // their own ephemeral bundles so they can independently assert
  // cleanup behavior.
  let material: EphemeralTlsMaterial;

  test.beforeAll(async () => {
    material = await createEphemeralTlsMaterial({ lifetimeDays: 1 });
  });

  test.afterAll(async () => {
    if (material) {
      await material.cleanup();
    }
  });

  test("every generated private key is owner-only (mode 0600)", () => {
    const keyPaths: string[] = [
      material.caKeyPath,
      material.serverKeyPath,
      material.postgresServerKeyPath,
      material.trustedListener.keyPath,
      material.trustedTeamExecutor.keyPath,
      material.trustedGateway.keyPath,
      material.wrongRoleCert.keyPath,
      material.wrongTeamCert.keyPath,
      material.untrustedCaCert.keyPath,
      material.untrustedCaKeyPath, // alias = untrustedCaCert.keyPath
      material.expiredCert.keyPath,
    ];
    for (const keyPath of keyPaths) {
      expect(modeOf(keyPath), `key file ${keyPath} is owner-only (0600)`).toBe(
        0o600,
      );
    }
  });

  test("every key-bearing temp directory is owner-only (mode 0700)", () => {
    const dirs: string[] = [material.tempDir, material.untrustedCaDir];
    for (const dir of dirs) {
      expect(
        modeOf(dir),
        `key-bearing temp dir ${dir} is owner-only (0700)`,
      ).toBe(0o700);
    }
  });

  test("public certs remain world-readable (>= 0644) so TLS clients can load them", () => {
    // The certs intentionally keep permissive modes; the contract
    // asserts that the fixture did not accidentally chmod 0600 the
    // certs as a side-effect of fixing the keys.
    const certPaths: string[] = [
      material.caCertPath,
      material.serverCertPath,
      material.postgresServerCertPath,
      material.trustedListener.certPath,
      material.trustedTeamExecutor.certPath,
      material.trustedGateway.certPath,
      material.wrongRoleCert.certPath,
      material.wrongTeamCert.certPath,
      material.untrustedCaCert.certPath,
      material.expiredCert.certPath,
    ];
    for (const certPath of certPaths) {
      const mode = modeOf(certPath);
      expect(mode & 0o004, `cert ${certPath} is world-readable`).not.toBe(0);
      expect(mode & 0o400, `cert ${certPath} is owner-readable`).not.toBe(0);
    }
  });

  test("cleanup() is idempotent: calling it twice does not throw", async () => {
    // Generate a fresh bundle so this test owns its cleanup
    // semantics without competing with the beforeAll bundle.
    const local = await createEphemeralTlsMaterial({ lifetimeDays: 1 });
    await local.cleanup();
    // Second call must not throw — the directory is already gone.
    await expect(local.cleanup()).resolves.toBeUndefined();
  });

  test("cleanup() propagates a real removal failure (does not silently swallow)", async () => {
    // Generate a fresh bundle. After generation, chmod the parent
    // dir to mode 0500 (read+execute only; no write bit on the
    // parent) and chmod every file inside to mode 0400 (read
    // only). Under these conditions rmSync({recursive:true,
    // force:true}) on the bundle's tempDir cannot remove the
    // contained files (no write bit on the parent), so the call
    // throws EPERM/EACCES. cleanup() must propagate that error
    // so the test fails loudly rather than silently leaving the
    // files on disk.
    const local = await createEphemeralTlsMaterial({ lifetimeDays: 1 });
    const bundle = pathResolve(local.tempDir);
    try {
      // Lock the bundle down: parent dir + every file mode 0400.
      chmodSync(bundle, 0o500);
      // We can't enumerate the bundle contents without reading
      // them; the rm below will recurse and hit the permission
      // wall at the first unremovable file.
      let caught: unknown;
      try {
        await local.cleanup();
      } catch (err) {
        caught = err;
      }
      expect(
        caught,
        "cleanup() must reject when the bundle cannot be removed",
      ).toBeDefined();
      expect((caught as Error).message).toMatch(/EACCES|EPERM|permission/i);
    } finally {
      chmodSync(bundle, 0o700);
      await local.cleanup();
    }
  });
});
