apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: flowai-executor-k8s
servers: 1
agents: 0
options:
  k3d:
    wait: true
    timeout: 180s
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --kubelet-arg=feature-gates=KubeletInUserNamespace=true
        nodeFilters:
          - server:0
      - arg: --kube-proxy-arg=conntrack-max-per-core=0
        nodeFilters:
          - server:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
