// Per-identity APIRequestContext fixtures for the state-registry
// qa-e2e suite. The fixtures provide immutable per-identity
// contexts. Team-owned identities (listener, team-owned Executor,
// trusted Gateway) carry an immutable team_id and emit the
// X-FlowAI-Team-Id header. Identities with no team binding
// (system-owned Executor, system administrator) emit NO
// X-FlowAI-Team-Id and carry no team identifier. Identity metadata
// travels as X-FlowAI-* request headers; the State Registry contract
// forbids those headers from authorizing anything on their own, so
// protected endpoints must remain unimplemented and must reject these
// requests without reading or returning tenant data.
//
// The exported team constants `TeamA` and `TeamB` exist only for the
// harness_smoke RED smoke check; contract tests MUST build per-test
// team-bound identity contexts through the `*For(teamId, ...)`
// constructors so the X-FlowAI-Team-Id / X-FlowAI-Source-System-Id /
// X-FlowAI-Listener-Identity / X-FlowAI-Operator-Id headers match the
// actual `team_id`, `source_system_id`, `listener_identity` returned
// from the documented registration boundaries.
import { request, type APIRequestContext } from "@playwright/test";

export type IdentityRole =
  | "listener"
  | "team-executor"
  | "system-executor"
  | "gateway"
  | "admin";

export interface IdentityContext {
  readonly id: string;
  readonly role: IdentityRole;
  readonly teamId?: string;
  readonly description: string;
  api(baseUrl: string): Promise<APIRequestContext>;
  attach(): Readonly<Record<string, string>>;
}

function contextId(
  role: IdentityRole,
  teamId: string | undefined,
  suffix = "",
): string {
  return `${role}${teamId ? ":" + teamId : ""}${suffix ? ":" + suffix : ""}`;
}

function buildHeaders(
  role: IdentityRole,
  teamId: string | undefined,
  bindings?: {
    listenerIdentity?: string;
    sourceSystemId?: string;
    executorId?: string;
    operatorId?: string;
    teamName?: string;
    adminSubject?: string;
  },
): Record<string, string> {
  const headers: Record<string, string> = {
    "X-FlowAI-Role": role,
    "X-FlowAI-Request-Id": `req-${role}-${teamId ?? "system"}-${Math.random().toString(36).slice(2, 10)}`,
  };
  if (teamId !== undefined) {
    headers["X-FlowAI-Team-Id"] = teamId;
  }
  if (role === "gateway" && teamId !== undefined) {
    headers["X-FlowAI-Operator-Id"] = bindings?.operatorId ?? `op-${teamId}`;
    headers["X-FlowAI-Team-Name"] = bindings?.teamName ?? `Team ${teamId}`;
  }
  if (role === "team-executor" && teamId !== undefined) {
    headers["X-FlowAI-Executor-Id"] =
      bindings?.executorId ??
      `exec-${teamId}-${Math.random().toString(36).slice(2, 8)}`;
  }
  if (role === "system-executor") {
    headers["X-FlowAI-Executor-Id"] =
      bindings?.executorId ??
      `exec-system-${Math.random().toString(36).slice(2, 8)}`;
  }
  if (role === "listener" && teamId !== undefined) {
    headers["X-FlowAI-Listener-Identity"] =
      bindings?.listenerIdentity ??
      `listener-${teamId}-${Math.random().toString(36).slice(2, 6)}`;
    headers["X-FlowAI-Source-System-Id"] =
      bindings?.sourceSystemId ?? `ss-${teamId}`;
  }
  if (role === "admin") {
    headers["X-FlowAI-Admin-Subject"] =
      bindings?.adminSubject ??
      `admin-${Math.random().toString(36).slice(2, 8)}`;
  }
  return headers;
}

export class ImmutableIdentityContext implements IdentityContext {
  readonly id: string;
  readonly role: IdentityRole;
  readonly teamId?: string;
  readonly description: string;
  private readonly _headers: Readonly<Record<string, string>>;

  constructor(
    role: IdentityRole,
    teamId: string | undefined,
    description: string,
    bindings?: Parameters<typeof buildHeaders>[2],
  ) {
    this.id = contextId(role, teamId);
    this.role = role;
    this.teamId = teamId;
    this.description = description;
    this._headers = Object.freeze(buildHeaders(role, teamId, bindings));
  }

  async api(baseUrl: string): Promise<APIRequestContext> {
    return await request.newContext({
      baseURL: baseUrl,
      extraHTTPHeaders: { ...this._headers },
    });
  }

  attach(): Readonly<Record<string, string>> {
    return this._headers;
  }
}

// Harness_smoke-only constants. Contract tests MUST NOT use these as
// the authenticated team_id because the actual registered team_id is
// generated by POST /admin/teams and is unrelated to these strings.
export const TeamA = "team-a";
export const TeamB = "team-b";

export function listenerTeamA(): IdentityContext {
  return new ImmutableIdentityContext(
    "listener",
    TeamA,
    "authorized listener for team-a",
  );
}

export function listenerTeamB(): IdentityContext {
  return new ImmutableIdentityContext(
    "listener",
    TeamB,
    "authorized listener for team-b",
  );
}

export function teamExecutorTeamA(): IdentityContext {
  return new ImmutableIdentityContext(
    "team-executor",
    TeamA,
    "team-owned Executor bound to team-a",
  );
}

export function teamExecutorTeamB(): IdentityContext {
  return new ImmutableIdentityContext(
    "team-executor",
    TeamB,
    "team-owned Executor bound to team-b",
  );
}

export function systemExecutor(): IdentityContext {
  return new ImmutableIdentityContext(
    "system-executor",
    undefined,
    "system-owned Executor with no team binding",
  );
}

export function gatewayTeamA(): IdentityContext {
  return new ImmutableIdentityContext(
    "gateway",
    TeamA,
    "trusted API Gateway forwarding operator-team-a",
  );
}

export function gatewayTeamB(): IdentityContext {
  return new ImmutableIdentityContext(
    "gateway",
    TeamB,
    "trusted API Gateway forwarding operator-team-b",
  );
}

export function systemAdministrator(): IdentityContext {
  return new ImmutableIdentityContext(
    "admin",
    undefined,
    "authenticated system administrator with no team binding",
  );
}

// Dynamic per-test team-bound identity constructors. The supplied
// team_id is the `team_id` returned by POST /admin/teams; the
// supplied source_system_id and listener_identity are the values
// returned by POST /admin/source-systems; the supplied operator_id is
// the verified Gateway operator identifier. Using these constructors
// guarantees that the X-FlowAI-* request headers match the actual
// canonical team / source-system / operator records the Registry
// persists, satisfying the contract rule that copy-pasted headers do
// not authenticate.

export interface ListenerBinding {
  readonly listenerIdentity: string;
  readonly sourceSystemId: string;
}

export interface TeamBinding {
  readonly teamId: string;
  readonly listenerIdentity: string;
  readonly sourceSystemId: string;
}

export interface OperatorBinding {
  readonly teamId: string;
  readonly operatorId: string;
  readonly teamName?: string;
}

export interface ExecutorBinding {
  readonly teamId: string;
  readonly executorId: string;
}

export function listenerFor(team: TeamBinding): IdentityContext {
  return new ImmutableIdentityContext(
    "listener",
    team.teamId,
    `authorized listener bound to team ${team.teamId}`,
    {
      listenerIdentity: team.listenerIdentity,
      sourceSystemId: team.sourceSystemId,
    },
  );
}

export function teamExecutorFor(b: ExecutorBinding): IdentityContext {
  return new ImmutableIdentityContext(
    "team-executor",
    b.teamId,
    `team-owned Executor ${b.executorId} bound to team ${b.teamId}`,
    { executorId: b.executorId },
  );
}

export function systemExecutorWithId(executorId: string): IdentityContext {
  return new ImmutableIdentityContext(
    "system-executor",
    undefined,
    `system-owned Executor ${executorId} with no team binding`,
    { executorId },
  );
}

export function gatewayFor(b: OperatorBinding): IdentityContext {
  return new ImmutableIdentityContext(
    "gateway",
    b.teamId,
    `trusted API Gateway forwarding operator ${b.operatorId} for team ${b.teamId}`,
    { operatorId: b.operatorId, teamName: b.teamName ?? `Team ${b.teamId}` },
  );
}

export function adminWithSubject(subject: string): IdentityContext {
  return new ImmutableIdentityContext(
    "admin",
    undefined,
    `authenticated system administrator ${subject}`,
    { adminSubject: subject },
  );
}

export function AllIdentities(): IdentityContext[] {
  return [
    listenerTeamA(),
    listenerTeamB(),
    teamExecutorTeamA(),
    teamExecutorTeamB(),
    systemExecutor(),
    gatewayTeamA(),
    gatewayTeamB(),
    systemAdministrator(),
  ];
}
