releases:
  - name: executor-k8s-openhands
    namespace: flowai-executor-k8s
    createNamespace: true
    chart: ./chart
    values:
      - ./values-k3d.yaml
      - storageClass:
          create: false
          name: local-path
    wait: true
    timeout: 180
