{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: executor-k8s-openhands-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
