{{- if .Values.executor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: executor-k8s-openhands
  labels:
    app.kubernetes.io/name: executor-k8s-openhands
spec:
  selector:
    app.kubernetes.io/name: executor-k8s-openhands
  ports:
    - name: http
      port: 8030
      targetPort: http
{{- end }}
